FROM docker.io/oracleinanutshell/oracle-xe-11g

MAINTAINER "CHOI GOOKHYUN<tang@dustbox.kr>"


ADD table_create.sql /docker-entrypoint-initdb.d/
ADD db_init_setting_script.sh /docker-entrypoint-initdb.d/
